// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for macos - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyBNnCKZ3LWTW136jid-1ekZdN5f3PdL5fI',
//     appId: '1:80668215372:web:d87b8511b20fa421858ce9',
//     messagingSenderId: '80668215372',
//     projectId: 'flutterproject-6b61f',
//     authDomain: 'flutterproject-6b61f.firebaseapp.com',
//     storageBucket: 'flutterproject-6b61f.appspot.com',
//     measurementId: 'G-HL81K69X08',
//   );
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyAmhgZMaiYduaYUJEOPy7L_PDBoBC5bF7g',
//     appId: '1:80668215372:android:d77cf39087074a02858ce9',
//     messagingSenderId: '80668215372',
//     projectId: 'flutterproject-6b61f',
//     storageBucket: 'flutterproject-6b61f.appspot.com',
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyAcU_kR62o6f1uTPoVxMwfvxcrqqxGUx4s',
//     appId: '1:80668215372:ios:df03c24ff2a68a78858ce9',
//     messagingSenderId: '80668215372',
//     projectId: 'flutterproject-6b61f',
//     storageBucket: 'flutterproject-6b61f.appspot.com',
//     iosClientId: '80668215372-npdp1v75minft0dp95rb4v0jth07p8vo.apps.googleusercontent.com',
//     iosBundleId: 'com.example.flutterProject',
//   );
// }
